DROP DATABASE if EXISTS MY_SHOPPING_CART;
CREATE DATABASE IF NOT EXISTS MY_SHOPPING_CART;
USE MY_SHOPPING_CART;

DROP TABLE IF EXISTS `UserTable`;
CREATE TABLE `UserTable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` varchar(30) NOT NULL,
  `user_password` varchar(30) NOT NULL,
  `user_email` varchar(50) DEFAULT NULL,
  `user_level` SMALLINT(8) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=255 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `TransactionTable`;
CREATE TABLE `TransactionTable` (
  `zid` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT DEFAULT NULL,
  `product_id` INT DEFAULT NULL,
  `transaction_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `transaction_price` DECIMAL(5,2) DEFAULT NULL,
  PRIMARY KEY (`zid`)
) ENGINE=MyISAM AUTO_INCREMENT=255 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ProductTable`;
CREATE TABLE `ProductTable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` varchar(50) DEFAULT NULL,
  `product_description` varchar(250) DEFAULT NULL,
  `product_msrp` DECIMAL(5,2) DEFAULT NULL,
  `tax_id` INT  DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=255 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `TaxTable`;
CREATE TABLE `TaxTable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tax_state` varchar(50) DEFAULT NULL,
  `tax_percent` DECIMAL(5,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=255 DEFAULT CHARSET=latin1;


